### ISSUE TITLE
slopegraphs

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#118]
i'm confused.
why don't we have sample versions for Mantel and Dcorr?
can't we just run the same sample mgc on them?

also, i updated the slopegraph plot in the meantime.
the word "sample" was too in the middle.

**Comment by cshen6** [comment]
you didn't push the figure?

we don't have sample mgc for dcorr, because dcorr is biased, i.e., not of mean 0 for each local dcorr, so we cannot use the absolute magnitude to select significant local dcorr. 

we can still have the sample versions for dcorr and mantel, see page 30 second paragraph, by essentially taking Heller's suggestion, i.e., validate significant p-values within a region, then run permutation test again by using the p-value as a test statistic. But it is much slower, more difficult to explain in main paper,  and doesn't gain us more in testing performance than current sample MGC for mcorr only.

**Comment by cshen6** [comment]
in summary, we can have them, as we said in appendix.

but since the current simple scheme works so well already, we don't need to go for a more complex / slower sample version.

**Comment by jovo** [comment]
I see. We should explain that somewhere in text. Probably appendix.

**Comment by cshen6** [comment]
I think it is pretty much well explained in appendix mgc section last paragraph.

I will leave a \cs mark there so we can take a look together later.

**Comment by cshen6** [comment]
I rephrased the last two paragraphs there, so you can see why we really tailor sample mgc for mcorr, and the general strategy. If you like it, just delete the \cs comment below.

**Comment by jovo** [comment]
cool!
