### ISSUE TITLE
appendices and pseudocode

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#154]
each should be mentioned in the main text, in the right order.

ie, the first reference to an Appendix should be Appendix A, etc.

currently, many of them are not even mentioned in the main text.

**Comment by cshen6** [comment]
ok I will fixed that, and close this issue after fixing.

**Comment by cshen6** [comment]
I have arranged all algs and all appendix sections to appear in the main text in their respective order.

Note that I also changed the figure labels from S1,S2,... to E1, E2, etc., because the appendix figure section is now Section E & it feels more logical to name figures following the  section label.

I also did the same label for algorithm, so they are alg C1, C2,..., because algorithm section is appendix C.

If you don't like the label naming, let me know and I can easily tweak them
