### ISSUE TITLE
fig A

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#38]
3d scatter --> mcorr A & B --> scatter + edges --> Atilde .\* Btilde --> g_{k,l}(data)

**Comment by cshen6** [comment]
Attached pls find a demo.

_type6.png_ is for the quadratic case, at n=20, dimension=1, no noise.

Instead of showing mcorr A&B, I find it more appealing to show the global &
local distance for X and Y (i.e., C and D in the paper).

So it is C & D -> local C & D by mcorr; the local distances appear to be
more similar to each other.

The _type19.png_ (for uncorrelated binomial), however, illustrate the point
most clearly among all our simulations. Clearly the un-similar part of the
global distance gets eliminated in the local version.

But the scatter + edge plot is not showing much, see _type 6b.png_; it is
merely connecting the neighbors of each point (x,y).

What do you think? Are they showing anything you are interested to see?

**Comment by jovo** [comment]
what do you mean "attached"?

**Comment by jovo** [comment]
for some setting:

scatter --> distance matrices (stacked) --> dcorr matrices (stacked) --> local dcorr matrices (stacked) --> hadamard product

**Comment by cshen6** [comment]
Attached a sampler of plots, corresponding to:
quadratic, W shape, two parabola, spiral, sine period 1/2, and uncorrelated
binomial.

For each plot:
The first row is the two distance matrices;
second row the global dcorr matrices;
third row the local dcorr;
the last row for the global and local dcorr product.

In particular, for the last row, you may observe that our local
dcorr product is able to exclude most global product terms that are
negative; such that the sum of the local dcorr product is larger than the
sum of the global dcorr product.

The figures are more clear than the actual numbers; but not too
illustrative if we put them in the papers. What do you think?

On Mon, Feb 15, 2016 at 5:11 PM, joshua vogelstein <notifications@github.com
