### ISSUE TITLE
next round

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#55]
### @cshen6
- [x] make sure all links go to the right place (eg, pseudocode, appendix, etc.)
- [x] make sure all references are ok
- [x] fig1: to discuss
- [x] order pseudocodes based on their mention in the main text
- [x] fix S2.3.1 & S2.3.2 to only mention MGC_M
- [x] power goes up for high-d spiral as d increases, that can't be right?
- [x] update 3.3 (and remove final column from figure)
- [x] in discussion:
  - O(n \* max(k,l) log n) if we bound k,l
  - finite sample theory
  - classificaiton

**Comment by cshen6** [comment]
Still experimenting on figure 1 and hd spiral. But should be done in a day and report back.

Everything else is fixed, but I made some minor changes and left note by \jv in tex, 
for us to talk through.

The discussion bullet points are added accordingly too, except: 
**◦O(n \* max(k,l) log n) if we bound k,l.**
Because sorting each column would require O(n log n) generally, or O(n log k ) if we bound k.
So it should be O(n^2 log (max(k,l))) instead, if we want to add this one?
But I feel this is a relatively small / algorithmic point that is more appropriate in appendix algorithm part?

**Comment by cshen6** [comment]
figure 1 updated in tex, with a lengthy caption...
let us chat on Skype tomorrow morning for remaining tex queries and any other problem?

**Comment by jovo** [comment]
looks so great!
some minor things:
- [x] remove "_2" from norm, part of the key is that it is NOT just euclidean!
- [x] make arrowheads bigger
- [x] i'd put scalebar on the A.*B one (left side), and add the min and the max
- [x] label the "Multiscale Power Map" accordingly.
- [x] as always, most of the fonts sizes are too small
- [x] make the lines thicker in the density function plot
- [x] use the same colormap for the MPM here as in the other figures
- [x] power for global is really 0.5 in this setting?
- [x] label the dots with their p-value, rather than putting it below
- [x] give it a title
- [x] use two different symbols for the two different algorithms

we are definitely closing in...

**Comment by cshen6** [comment]
Figure 1 solved...a few concern:
1. if we use same colormap for MPM as in other figure, almost everywhere is high power except global, in this case it is more difficult to make the optimal scale obvious.
2. For the density plot, labeling the p-value on the plot is too difficult, visually speaking (the font will be too small to squeeze in). 

So I instead put the optimal scale and p-value number in the caption.
1. Not sure what you mean for different symbols? you mean in density plot, we use two different symbols instead of the black/gray dots of MGC/Mcorr?

**Comment by jovo** [comment]
>    1.
> 
>    if we use same colormap for MPM as in other figure, almost everywhere
>    is high power except global, in this case it is more difficult to make the
>    optimal scale obvious.
> 
> we should use the same colormap then, but rescaled appropriately.
> 
>    1.
> 
>    For the density plot, labeling the p-value on the plot is too
>    difficult, visually speaking (the font will be too small to squeeze in).
> 
> you don't need a legend.
> above the gray dot (make it a gray something else, star, triangle, etc.),
> write Mcorr p = 0.24
> and above the black dot, write MGC p < 0.0001.

also, we never write p=0, always < 1/r, for whatever r we used.

>    1.
> 
> So I instead put the optimal scale and p-value number in the caption.
> 1. Not sure what you mean for different symbols? you mean in density
>    plot, we use two different symbols instead of the black/gray dots of
>    MGC/Mcorr?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/MGC/issues/55#issuecomment-228345687, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcrWDviQb3RbSsoPygUMB-RsMNfKyks5qO9vlgaJpZM4I3VHe
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York
