### ISSUE TITLE
5 factor personality data

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#68]
did we ever run MGC on that data?
if not, why not?
not saying that we should for this paper, but we should in general, i would think....

**Comment by cshen6** [comment]
Because our MGC p-value algorithm no longer returns significant p-value!

indeed there are roughly 1/3 local scales that are significant on their own, but the significant region doesn't pass the validation of our algorithm. So the global scale is taken instead for MGC.

Note that those local scales may be "truly" significant. But without more data we are not sure they are true positives or not.

**Comment by jovo** [comment]
can you send me the pvalue map?
this might be a good usecase for considering a "better" selection algorithm

**Comment by cshen6** [comment]
ok see attached (in email) for brain vs personality heatmap.
