### ISSUE TITLE
power = alpha under null

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#69]
don't we need to prove that?

otherwise, i have a test who's power goes to 1: always reject no matter what.

**Comment by cshen6** [comment]
once we determine the optimal scale for MGC, then power = alpha under null. 
Yes, it is trivially true.

we can say it in the theoretical section just in one sentence, if you wish.
Neither HHG nor dcorr proves this in a theorem though (they don't mention this at all as I recall), probably because it is too trivial.

**Comment by jovo** [comment]
i don't see why it is trivially true, but i do see why we should say it
(non-statisticians, such as me, will read this paper and wonder whether it
is true :)

On Wed, Jun 29, 2016 at 8:04 AM, cshen6 notifications@github.com wrote:

> once we determine the optimal scale for MGC, then power = alpha under
> null.
> Yes, it is trivially true.
> 
> we can say it in the theoretical section just in one sentence, if you wish.
> Neither HHG nor dcorr proves this in a theorem though (they don't mention
> this at all as I recall), probably because it is too trivial.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/MGC/issues/69#issuecomment-229336398, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjcrYjrFL_2BRf3z0GE7XbwWhWFTSgks5qQl9JgaJpZM4JAuAg
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
because once the optimal scale is fixed, MGC always distributes the same under the null and alternative, if the alternative is in fact also independent. So power = alpha.
(Note that if we allow the optimal scale to vary, then the above is not true)

ok, I will add it into  the theoretical section in one sentence? (a theorem will be an overkill I feel)

**Comment by jovo** [comment]
agreed.

On Wed, Jun 29, 2016 at 8:31 AM, cshen6 notifications@github.com wrote:

> because once the optimal scale is fixed, MGC always distributes the same
> under the null and alternative, if the alternative is in fact also
> independent. So power = alpha.
> (Note that if we allow the optimal scale to vary, then the above is not
> true)
> 
> ok, I will add it into the theoretical section in one sentence? (a theorem
> will be an overkill I feel)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/jovo/MGC/issues/69#issuecomment-229341938, or mute
> the thread
> https://github.com/notifications/unsubscribe/AACjctk_4XFHWTiGME4g07w_kADHqUUUks5qQmW9gaJpZM4JAuAg
> .

## 

the glass is all full:  half water, half air.
neurodata.io, jovo calendar
https://calendar.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York

**Comment by cshen6** [comment]
added in theoretical section after thm 1. feel free to move it if you wish.
