### ISSUE TITLE
appendix queries

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#74]
- [x] joint normal is defined pretty weirdly. it is not obvious to me that x & y are actually dependent?
- [x] log: we should define the log scale somewhere, maybe \log_2 is a fine way of doing it.
- [x] spiral: i don't understand why it is different from a circle other than r  is a r.v. rather than a constant?
- [x] should we provide the citation for each of the functions?
- [x] independent clouds: should we put 3^{-1/2} in the covariance so we can take it out of the equations (it might look nicer).
- [x] i removed the paragraph starting the supp figs section, it seemed redundant.
- [x] fig A4: it seems wrong for setting 19.
- [x] i don't understand the "centering" paragraphs.
- [x] "/" cannot really be used ever in formal writing.
- [x] i added a bunch of queries in the text too.
- [x] should all the paragraphs in D.1 actually be part of the captions for the corresponding algorithms? i think so? if so, we don't need a heading for D.1.
- [x] "clearly" should probably never be said, which reader can it help?
- [x] i made alg 1 perfect, used ":=" in all for statements, used \Linefor whenever possible, never have a comment spill over to next line, use "\rto" to re-assign variables, used \Require & \Ensure. please propagate to the other 4 algs.

**Comment by jovo** [comment]
- [x] i made \Lineif like your \Linefor.  do you like it? if so, let's use it in Alg 4.
- [x] Alg 5: lines 3-5 seem like they belong in a single for loop?
- [x] Alg 5 doesn't specify how to act in ties.

**Comment by cshen6** [comment]
All done. Will push after dinner.

Spirals are indeed different from circle, look at u. But otherwise same.
Figure A4 is right, but we should talk to see if we should adjust it.

We can give citations for each dependency, but it is unnecessary details, I think.

Removed all "/" and "clearly" in tex.

Let us talk about "single centering", and how to move D1 into captions.

Independent clouds do not have the problem you described.

The pseudo code always assumes there is no ties, which applies to all algs. Adding this special case will significantly lengthen all pseudo codes, without adding any new insight.

**Comment by jovo** [comment]
topics to discuss then:
- [x] pseudocode clean up
- [x] ties
- [x] single centering
- [x] other paper
