### ISSUE TITLE
table is wrong/weird

### ISSUE THREAD

**Issue by jovo** [neurodata/MGC-paper#83]
i don't understand the table, but i'm pretty sure it is wrong.

it is supposed to show that MGC _ignores_ pairs when there is a large distance in x or y (or both).

skype me when you get a chance?

**Comment by cshen6** [comment]
the table from save file is as follows:

 & Mantel & Mcorr & MGC \
 $\delta_x$(1,2) & -2.42 & -5.21 & -5.07  \
 $\delta_y$(1,2) & -1.58 & -0.91 & 0.12  \
 $\delta_x \times \delta_y$ & 3.82 & 4.74 & 0.61  \

\hline

 $\delta_x$(3,2) & 0.70 & -2.15 & 0.14  \
 $\delta_y$(3,2) & -0.91 & -0.90 & 0.12  \
 $\delta_x \times \delta_y$ & -0.63 & 1.93 & 0.02  \

Do you mean the last entry above should be 0 instead of 0.02?

It is zero pre-simple-centering of A^{k} and B^{l}, but not exactly zero
post-simple-centering.

I can change it to show pre-simple-centering results instead, if that is
what you mean?

On Thu, Aug 11, 2016 at 2:17 PM, joshua vogelstein <notifications@github.com

**Comment by cshen6** [comment]
updated code on github, and the table on overleaf.

You may need to generate fig A on your machine and update on github /
overleaf though, since its size by windows matlab is squeezy.
